<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class EmailSmsTemplatesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('email_sms_templates')->insert(
            array(
                array('id' => '1', 'act' => 'ACCOUNT_RECOVERY_CODE', 'name' => 'Account recovery code send', 'subj' => 'Account recovery code', 'email_body' => 'Your account recovery code is: {{code}}', 'sms_body' => 'Your account recovery code is: {{code}}', 'shortcodes' => '{"code":"Recovery code"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '2', 'act' => 'EVER_CODE', 'name' => 'Email Verification code send', 'subj' => 'Please verify your email address', 'email_body' => 'Your email verification code is: {{code}}', 'sms_body' => 'Your email verification code is: {{code}}', 'shortcodes' => '{"code":"Verification code"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '3', 'act' => 'SVER_CODE', 'name' => 'Phone Verification code send', 'subj' => 'Please verify your phone', 'email_body' => 'Your phone verification code is: {{code}}', 'sms_body' => 'Your phone verification code is: {{code}}', 'shortcodes' => '{"code":"Verification code"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '4', 'act' => 'PASS_RESET', 'name' => 'Password reset email', 'subj' => 'You have changed your password', 'email_body' => 'Your password has been changed successfully', 'sms_body' => 'Your password has been changed successfully', 'shortcodes' => '{"code":"Verification code"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '6', 'act' => 'WITHDRAW_PENDING', 'name' => 'Withdraw Pending', 'subj' => 'Withdraw Request Pending', 'email_body' => '{{amount}} Withdraw Request Successful Via {{method}}. Your Transaction Number {{trx}}. Charge {{charge}}', 'sms_body' => '{{amount}} Withdraw Request Successful Via {{method}}. Your Transaction Number {{trx}}. Charge {{charge}}', 'shortcodes' => '{"amount":"Withdraw Amount", "method":"Method Name","trx":"Transaction Number","charge":"Withdraw Charge"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '7', 'act' => 'TRADE_START', 'name' => 'Trading Start', 'subj' => 'Trade has been started', 'email_body' => '{{trade}} has been started with {{amount}}', 'sms_body' => '{{trade}} has been started with {{amount}}', 'shortcodes' => '{"amount":"Trade Amount", "trade":"Trade Name"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '8', 'act' => 'TRADE_END', 'name' => 'Trading End', 'subj' => 'Trade has been Ended', 'email_body' => '{{trade}} has been ended. {{amount}} has been refunded to your balance.', 'sms_body' => '{{trade}} has been ended. {{amount}} has been refunded to your balance.', 'shortcodes' => '{"trade":"Trade Name","amount":"Trade Amount/Return Amount}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '9', 'act' => 'TRADE_CLOSE', 'name' => 'Trading Closed', 'subj' => 'Trading has been closed', 'email_body' => '{{trade}} has been closed. You have collected {{profit}}.', 'sms_body' => '{{trade}} has been closed. You have collected {{profit}}.', 'shortcodes' => '{"trade":"Trade Name","profit":"Trading Profit"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '10', 'act' => '2FA_ENABLE', 'name' => 'Google Two Factor Enable', 'subj' => 'Google Two Factor verification is enabled', 'email_body' => 'Your verification code is: {{code}}', 'sms_body' => 'Your verification code is: {{code}}', 'shortcodes' => '{"trade":"Trade Name","profit":"Trading Profit"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '11', 'act' => '2FA_DISABLE', 'name' => 'Google Two Factor Disable', 'subj' => 'Google Two Factor verification is disabled', 'email_body' => 'Google two factor verification is disabled', 'sms_body' => 'Google two factor verification is disabled', 'shortcodes' => '{}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '13', 'act' => 'WITHDRAW_APPROVE', 'name' => 'Withdraw Approved', 'subj' => 'Withdraw Request has been approved', 'email_body' => '{{amount}} Withdraw Request Approved Successfully Via {{method}}. Your transaction number is {{trx}}. You should receive {{receive_amount}} after charge deduction {{charge}}', 'sms_body' => '{{amount}} Withdraw Request Approved Successfully Via {{method}}. Your transaction number is {{trx}}. You should receive {{receive_amount}} after charge deduction {{charge}}', 'shortcodes' => '{"amount":"Withdraw Amount", "method":"Method Name","trx":"Transaction Number","charge":"Withdraw Charge","receive_amount":"Receivable Amount" }', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '14', 'act' => 'WITHDRAW_REJECT', 'name' => 'Withdraw Reject', 'subj' => 'Withdraw Request has been rejected', 'email_body' => '{{amount}} Withdraw Request Has Been Rejected For {{method}}. Your transaction number is {{trx}}', 'sms_body' => '{{amount}} Withdraw Request Has Been Rejected For {{method}}. Your transaction number is {{trx}}', 'shortcodes' => '{"amount":"Withdraw Amount", "method":"Method Name","trx":"Transaction Number"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '15', 'act' => 'DEPOSIT_PENDING', 'name' => 'Deposit Pending', 'subj' => 'Deposit Request Pending', 'email_body' => '{{amount}} Deposit Request Successful Via {{method}}. Your Transaction Number {{trx}}. Charge {{charge}}', 'sms_body' => '{{amount}} Deposit Request Successful Via {{method}}. Your Transaction Number {{trx}}. Charge {{charge}}', 'shortcodes' => '{"amount":"Deposit Amount", "method":"Method Name","trx":"Transaction Number","charge":"Deposit Charge"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '16', 'act' => 'DEPOSIT_APPROVE', 'name' => 'Deposit Approved', 'subj' => 'Deposit Request has been approved', 'email_body' => '{{amount}} Deposit Request Approved Successfully Via {{method}}. Your transaction number is {{trx}}. You should receive {{receive_amount}} after charge deduction {{charge}}', 'sms_body' => '{{amount}} Deposit Request Approved Successfully Via {{method}}. Your transaction number is {{trx}}. You should receive {{receive_amount}} after charge deduction {{charge}}', 'shortcodes' => '{"amount":"Withdraw Amount", "method":"Method Name","trx":"Transaction Number","charge":"Withdraw Charge","receive_amount":"Receivable Amount" }', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '17', 'act' => 'DEPOSIT_REJECT', 'name' => 'Deposit Reject', 'subj' => 'Deposit Request has been rejected', 'email_body' => '{{amount}} Deposit Request Has Been Rejected For {{method}}. Your transaction number is {{trx}}', 'sms_body' => '{{amount}} Deposit Request Has Been Rejected For {{method}}. Your transaction number is {{trx}}', 'shortcodes' => '{"amount":"Withdraw Amount", "method":"Method Name","trx":"Transaction Number"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '18', 'act' => 'REF_COM', 'name' => 'Referral commission', 'subj' => 'You Got Referral commission', 'email_body' => 'Congratulation, You Got Level {{reflevel}} Referral Commission.', 'sms_body' => 'Congratulation, You Got Level {{reflevel}} Referral Commission.', 'shortcodes' => '{"reflevel":"Refer Level"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '19', 'act' => 'BAL_ADD', 'name' => 'Balance Add by Admin', 'subj' => 'Your balance has been credited', 'email_body' => 'Your balance has been credited with {{amount}}', 'sms_body' => 'Your balance has been credited with {{amount}}', 'shortcodes' => '{"amount":"Credited Amount"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '20', 'act' => 'BAL_SUB', 'name' => 'Balance Subtracted by Admin', 'subj' => 'Your balance has been debited', 'email_body' => 'Your balance has been debited by {{amount}}', 'sms_body' => 'Your balance has been debited by {{amount}}', 'shortcodes' => '{"amount":"Debited Amount"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '21', 'act' => 'BAL_SEND', 'name' => 'Balance Send', 'subj' => 'Balance Transfer Successfully', 'email_body' => 'Balance transferred successfully complete. You send  {{amount}}  to  {{name}}  And charge to transfer  {{charge}}. Your current balance is {{balance_now}}', 'sms_body' => 'Balance transferred successfully complete. You send  {{amount}}  to  {{name}}  And charge to transfer  {{charge}}. Your current balance is {{balance_now}}', 'shortcodes' => '{"amount":"Send Amount", "name":"Receiver Name","charge":"Transfer charge" ,"balance_now":" After Balance"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-09-25 00:58:46'),
                array('id' => '22', 'act' => 'bal_receive', 'name' => 'Balance Received', 'subj' => 'Balance Received Successfully', 'email_body' => 'Balance received successfully. You got {{amount}} from {{name}}  And charge {{charge}}. Your current balance is {{balance_now}}', 'sms_body' => 'Balance transferred successfully complete. You send  {{amount}}  to  {{name}}  And charge to transfer  {{charge}}. Your current balance is {{balance_now}}', 'shortcodes' => '{"amount":"Send Amount", "name":"Receiver Name" ,"balance_now":" After Balance","charge":"Transfer charge"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-11-09 09:46:09'),
                array('id' => '27', 'act' => 'pan_purchased', 'name' => 'Purchased Plan', 'subj' => 'Purchased Plan', 'email_body' => 'Congratulation, You have successfully purchased {{name}}. {{price}}  subtract from your balance. And your current balance is {{balance_now}}.', 'sms_body' => 'Congratulation, You have successfully purchased {{name}}. {{price}}  subtract from your balance. And your current balance is {{balance_now}}.', 'shortcodes' => '{"price":"plan Price", "name":"Plan Name" ,"balance_now":" After Balance"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2019-11-09 09:46:09'),
                array('id' => '28', 'act' => 'referral_commission', 'name' => 'referral commission', 'subj' => 'New referral commission', 'email_body' => 'New referral commission : {{amount}}, from user {{username}}', 'sms_body' => 'New referral commission : {{amount}}, from user {{username}}', 'shortcodes' => '{"amount":"Referral commission", "username":"Referral commission from user"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2020-01-01 05:27:21'),
                array('id' => '29', 'act' => 'level_commission', 'name' => 'Level commission', 'subj' => 'New Level commission', 'email_body' => 'Congratulation, You Got  Level {{level_number}} Referral Commission. : {{amount}}, from user {{username}}', 'sms_body' => 'Congratulation, You Got  Level {{level_number}} Referral Commission. : {{amount}}, from user {{username}}', 'shortcodes' => '{"level_number":"Level", "amount":"Referral commission", "username":"Referral commission from user"}', 'email_status' => '1', 'sms_status' => '1', 'created_at' => '2019-09-25 00:04:05', 'updated_at' => '2020-01-01 05:27:21')
            )
        );
    }
}
